<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Storage.Infrastructure\Storage.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Storage.Web\Storage.Web.csproj" />
  </ItemGroup>

</Project>
